version: '3.5'

services:
  postgres:
    image: postgres:latest
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "200MB"
