name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./scripts
      run: docker build -t concurrency-control -f Dockerfile ../ && docker tag concurrency-control samluiz/concurrency-control
      
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push to DockerHub
      working-directory: ./scripts
      run: docker push samluiz/concurrency-control
